- name: Reviewed 
  color: 247DD3
  description: "Code is reviewed"
- name: Changes Request
  color: EC9900
  description: "Need changes in your code"
- name: Correction Done
  color: 31B525
  description: "Corrections have been applied, code review needed"
- name: Code Review Needed
  color: EACBEC
  description: "Need changes in your code"
- name: Conflicts
  color: EC2D29
  description: "Conflicts to solve"
- name: Fix
  color: 22E6EC
  description: "PR Fix"
